<?xml version="1.0" encoding="utf-8"?><Database Name="MATIX_GAME" Class="MatixDataDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=ORENF;Initial Catalog=MATIX_GAME;User ID=sa" SettingsObjectName="MatixDatabaseLibrary.Properties.Settings" SettingsPropertyName="MATIX_GAMEConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Games" Member="Games">
    <Type Name="Game">
      <Column Name="GameId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="HorizontalPlayerId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="VerticalPlayerId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="CellsMatrix" Type="System.Xml.Linq.XElement" DbType="Xml NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Game_PlayersHistory" Member="PlayersHistories" ThisKey="GameId" OtherKey="GameId" Type="PlayersHistory" />
      <Association Name="Game_GameActivity" Member="GameActivities" ThisKey="GameId" OtherKey="GameId" Type="GameActivity" />
      <Association Name="Player_Game" Member="Player" ThisKey="HorizontalPlayerId" OtherKey="PlayerId" Type="Player" IsForeignKey="true" />
      <Association Name="Player_Game1" Member="Player1" ThisKey="VerticalPlayerId" OtherKey="PlayerId" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PlayersLogin" Member="PlayersLogins">
    <Type Name="PlayersLogin">
      <Column Name="LoginId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="LoginTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IPAddress" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LogoutTime" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Reason" Type="System.String" DbType="NVarChar(80)" CanBeNull="true" />
      <Association Name="Player_PlayersLogin" Member="Player" ThisKey="PlayerId" OtherKey="PlayerId" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.PlayersHistory" Member="PlayersHistories">
    <Type Name="PlayersHistory">
      <Column Name="HistoryId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HistoryTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="GameId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Win" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="Score" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Game_PlayersHistory" Member="Game" ThisKey="GameId" OtherKey="GameId" Type="Game" IsForeignKey="true" />
      <Association Name="Player_PlayersHistory" Member="Player" ThisKey="PlayerId" OtherKey="PlayerId" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.GameActivities" Member="GameActivities">
    <Type Name="GameActivity">
      <Column Name="ActivityId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GameId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="PlayerId" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="ActivityTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CellRow" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CellColumn" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CellValue" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Game_GameActivity" Member="Game" ThisKey="GameId" OtherKey="GameId" Type="Game" IsForeignKey="true" />
      <Association Name="Player_GameActivity" Member="Player" ThisKey="PlayerId" OtherKey="PlayerId" Type="Player" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Players" Member="Players">
    <Type Name="Player">
      <Column Name="PlayerId" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreateTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(64) NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="Type" Type="System.String" DbType="VarChar(10)" CanBeNull="true" />
      <Association Name="Player_Game" Member="Games" ThisKey="PlayerId" OtherKey="HorizontalPlayerId" Type="Game" />
      <Association Name="Player_Game1" Member="Games1" ThisKey="PlayerId" OtherKey="VerticalPlayerId" Type="Game" />
      <Association Name="Player_PlayersLogin" Member="PlayersLogins" ThisKey="PlayerId" OtherKey="PlayerId" Type="PlayersLogin" />
      <Association Name="Player_PlayersHistory" Member="PlayersHistories" ThisKey="PlayerId" OtherKey="PlayerId" Type="PlayersHistory" />
      <Association Name="Player_GameActivity" Member="GameActivities" ThisKey="PlayerId" OtherKey="PlayerId" Type="GameActivity" />
    </Type>
  </Table>
  <Table Name="dbo.PlayerStatistics" Member="PlayerStatistics">
    <Type Name="PlayerStatistic">
      <Column Name="Email" Type="System.String" DbType="NVarChar(256) NOT NULL" CanBeNull="false" />
      <Column Name="NickName" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Games" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Winnings" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Score" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
</Database>