USE [master]
GO

/****** Object:  Database [MATIX_GAME]    Script Date: 06/22/2017 20:11:03 ******/
IF  EXISTS (SELECT name FROM sys.databases WHERE name = N'MATIX_GAME')
DROP DATABASE [MATIX_GAME]
GO

USE [master]
GO

/****** Object:  Database [MATIX_GAME]    Script Date: 06/22/2017 20:11:03 ******/
CREATE DATABASE [MATIX_GAME] ON  PRIMARY 
( NAME = N'MATIX_GAME', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\MATIX_GAME.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'MATIX_GAME_log', FILENAME = N'C:\Program Files (x86)\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\MATIX_GAME_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [MATIX_GAME] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MATIX_GAME].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MATIX_GAME] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MATIX_GAME] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MATIX_GAME] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MATIX_GAME] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MATIX_GAME] SET ARITHABORT OFF 
GO

ALTER DATABASE [MATIX_GAME] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [MATIX_GAME] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [MATIX_GAME] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MATIX_GAME] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MATIX_GAME] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MATIX_GAME] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MATIX_GAME] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MATIX_GAME] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MATIX_GAME] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MATIX_GAME] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MATIX_GAME] SET  DISABLE_BROKER 
GO

ALTER DATABASE [MATIX_GAME] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MATIX_GAME] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MATIX_GAME] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MATIX_GAME] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MATIX_GAME] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MATIX_GAME] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [MATIX_GAME] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MATIX_GAME] SET  READ_WRITE 
GO

ALTER DATABASE [MATIX_GAME] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MATIX_GAME] SET  MULTI_USER 
GO

ALTER DATABASE [MATIX_GAME] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MATIX_GAME] SET DB_CHAINING OFF 
GO

